base_path: .
preserve_hierarchy: true

export_languages:
  - zh-TW
  - zh-CN
  - ja
  - fr
  - de
  - es
  - it
  - pt-PT
  - pt-BR
  - ru
  - ko
  - uk
  - pl
  - tr

files:
  - source: /apps/web/src/i18n/locales/en/translation.json
    translation: /apps/web/src/i18n/locales/%locale%/%original_file_name%
